// Generated by scripts/build-namespace.mjs from src/constants/namespace.ts.
// Do not edit this file directly.

export const ASIDE_SUFFIX = ".lmgh-stale-";
export const ENV_PREFIX = "LMGH_";
export const LOCK_LOG_TAG = "[lmgh-lock]";
export const LOG_TAG = "[lmgh]";
export const NAMESPACE = "lmgh";
export const NOTIFY_CONFIG_FILE = ".lmgh-config.json";
export const PLUGIN_NAME = "let-me-go-home";
export const PROJECT_CONFIG_FILE = "lmgh.jsonc";
export const STATE_DIR = ".lmgh";
export const USER_CONFIG_DIR = "claude-lmgh";
export const WORKSPACE_MARKER = ".lmgh-workspace";

export function statePath(...segments) {
    return segments.length > 0 ? `${STATE_DIR}/${segments.join('/')}` : STATE_DIR;
}
